// electron/scripts/before-pack.js
// electron-builder `beforePack` hook. Generates electron/credentials.env so the
// packaged desktop app can seed %APPDATA%\EditFactory\.env on first run (see
// seedDesktopEnv() in src/main.js) and connect to the SAME Supabase cloud as the
// web app — real projects/clips + per-profile API keys.
//
// The file holds ONLY the anon SUPABASE_URL + SUPABASE_KEY (RLS-off; the same key
// is already public in the frontend JS bundle, so this is no new exposure). It is
// NEVER committed (electron/.gitignore) and is regenerated on every build.
//
// Runs for every electron-builder invocation, including the fast
// `npx electron-builder --win --dir` iteration path that bypasses npm scripts.

const fs = require('fs');
const path = require('path');

/** Minimal .env parser — KEY=VALUE lines, ignores blanks and # comments. */
function readEnvFile(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const raw of fs.readFileSync(file, 'utf-8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

exports.default = async function beforePack() {
  // electron/scripts/ -> electron/ -> project root
  const projectRoot = path.resolve(__dirname, '..', '..');
  const projectEnv = readEnvFile(path.join(projectRoot, '.env'));

  // Env vars win over the project .env so CI can inject without a checked-in file.
  const url = process.env.SUPABASE_URL || projectEnv.SUPABASE_URL || '';
  const key = process.env.SUPABASE_KEY || projectEnv.SUPABASE_KEY || '';

  if (!url || !key) {
    throw new Error(
      'before-pack: SUPABASE_URL / SUPABASE_KEY not found in env or project .env — ' +
      'cannot generate credentials.env. Set them before building so the packaged ' +
      'desktop app can reach Supabase.'
    );
  }

  const target = path.join(__dirname, '..', 'credentials.env');
  const body =
    '# Generated by scripts/before-pack.js — do NOT commit. Anon Supabase creds only.\n' +
    `SUPABASE_URL=${url}\n` +
    `SUPABASE_KEY=${key}\n`;
  fs.writeFileSync(target, body, 'utf-8');
  console.log(`[before-pack] Wrote ${target} (SUPABASE_URL + SUPABASE_KEY)`);
};
