// electron/scripts/before-pack.js
// electron-builder `beforePack` hook. Generates electron/credentials.env so the
// packaged desktop app can seed %APPDATA%\EditFactory\.env on first run (see
// seedDesktopEnv() in src/main.js) and connect to the SAME Supabase cloud as the
// web app — real projects/clips + per-profile API keys.
//
// The file holds only desktop-safe cloud configuration: the anon Supabase
// connection and the public media URL used by Buffer. It never contains a
// service-role key, is never committed, and is regenerated on every build.
//
// Runs for every electron-builder invocation, including the fast
// `npx electron-builder --win --dir` iteration path that bypasses npm scripts.

const fs = require('fs');
const path = require('path');
const { readEnvFile } = require('../src/desktop-env');

exports.default = async function beforePack() {
  // electron/scripts/ -> electron/ -> project root
  const projectRoot = path.resolve(__dirname, '..', '..');
  const projectEnv = readEnvFile(path.join(projectRoot, '.env'));

  // Env vars win over the project .env so CI can inject without a checked-in file.
  const url = process.env.SUPABASE_URL || projectEnv.SUPABASE_URL || '';
  const key = process.env.SUPABASE_KEY || projectEnv.SUPABASE_KEY || '';
  const minioPublicUrl =
    process.env.MINIO_PUBLIC_URL || projectEnv.MINIO_PUBLIC_URL || '';

  if (!url || !key || !minioPublicUrl) {
    throw new Error(
      'before-pack: SUPABASE_URL / SUPABASE_KEY / MINIO_PUBLIC_URL missing — ' +
      'cannot generate credentials.env. Set them before building so the packaged ' +
      'desktop app can reach Supabase and provide Buffer with public video URLs.'
    );
  }

  const target = path.join(__dirname, '..', 'credentials.env');
  const body =
    '# Generated by scripts/before-pack.js - do NOT commit. Safe desktop cloud configuration only.\n' +
    `SUPABASE_URL=${url}\n` +
    `SUPABASE_KEY=${key}\n` +
    `MINIO_PUBLIC_URL=${minioPublicUrl}\n`;
  fs.writeFileSync(target, body, 'utf-8');
  console.log(`[before-pack] Wrote ${target} (Supabase anon config + MINIO_PUBLIC_URL)`);
};
