var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/calendar/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1td1yxl._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xlg365.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zsutup._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/_next-internal_server_app_calendar_page_actions_1dm51cw.js")
R.m(26835)
module.exports=R.m(26835).exports
