// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automations">> = Specific
  const handler = {} as typeof import("../../src/app/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/batch-generate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/batch-generate">> = Specific
  const handler = {} as typeof import("../../src/app/batch-generate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/batch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/batch">> = Specific
  const handler = {} as typeof import("../../src/app/batch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/clipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clipping">> = Specific
  const handler = {} as typeof import("../../src/app/clipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/create-image/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-image">> = Specific
  const handler = {} as typeof import("../../src/app/create-image/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/create-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-video">> = Specific
  const handler = {} as typeof import("../../src/app/create-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/librarie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/librarie">> = Specific
  const handler = {} as typeof import("../../src/app/librarie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../src/app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/login/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/media-library">> = Specific
  const handler = {} as typeof import("../../src/app/media-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-library">> = Specific
  const handler = {} as typeof import("../../src/app/product-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/product-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-video">> = Specific
  const handler = {} as typeof import("../../src/app/product-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedule">> = Specific
  const handler = {} as typeof import("../../src/app/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/segments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/segments">> = Specific
  const handler = {} as typeof import("../../src/app/segments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../src/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tts-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tts-library">> = Specific
  const handler = {} as typeof import("../../src/app/tts-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/usage">> = Specific
  const handler = {} as typeof import("../../src/app/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/wiki/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wiki">> = Specific
  const handler = {} as typeof import("../../src/app/wiki/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
