var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/signup/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__110l2wz._.js")
R.c("server/chunks/ssr/node_modules_0ev7kv1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1cmz_yn.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zsutup._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/_next-internal_server_app_signup_page_actions_032y11p.js")
R.m(13697)
module.exports=R.m(13697).exports
